[build]
  # This is where Netlify will look for your lambda functions.
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/"
  to = "/web/index.html"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/web/index.html"
  status = 200

[[redirects]]
  from = "/style.css"
  to = "/web/style.css"
  status = 200

[[redirects]]
  from = "/manifest.json"
  to = "/web/manifest.json"
  status = 200

[[redirects]]
  from = "/app.js"
  to = "/web/app.js"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200  

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/redirect"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Referrer Policy is a new header that allows a site to control how much information the browser includes with navigations away from a document and should be set by all sites.
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Don't load any resource type not explicitly enabled
    # Disable plugins like Flash or Silverlight
    # Load images, scripts, stylesheets and fonts from self
    ## Content-Security-Policy = "upgrade-insecure-requests" <- this did not work tho
    # Prevent browsers from incorrectly detecting non-scripts as scripts
    X-Content-Type-Options = "nosniff"
    # Block site from being framed with X-Frame-Options and CSP
    Content-Security-Policy = "frame-ancestors 'self';"
    # Basic one if one above won't work
    # Content-Security-Policy = "default-src 'self';"
    # For future testing, refer to https://github.com/kodadot/nft-gallery/issues/540
    # Permissions-Policy = "interest-cohort=()"